spring:
  profiles:
    active: '@spring.profiles.active@'
---
spring:
  profiles: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  port: 8443
mvc:
  async:
    request-timeout: -1
---
spring:
  profiles: realtest
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  port: 8443
mvc:
  async:
    request-timeout: -1
---