spring:
  profiles:
    active: '@spring.profiles.active@'
---
spring:
  profiles: local

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: '/bforutonamanagermenttest'
  port: 8443
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl

forutona:
  serviekeypath: C:\\Users\\backho\\Desktop\\forutonadata\\adminsdkservicekey\\forutona-firebase-adminsdk-p6ho6-ab85124646.json
  storgeserviekeypath: C:\\Users\\backho\\Desktop\\forutonadata\\adminsdkservicekey\\Forutona-3539edf2b36d.json
---
spring:
  profiles: realtest

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

forutona:
  serviekeypath: /home/forutona/servicekeys/forutona-firebase-adminsdk-p6ho6-ab85124646.json
  storgeserviekeypath: /home/forutona/servicekeys/Forutona-3539edf2b36d.json

---