spring:
  profiles:
    active: '@spring.profiles.active@'
---
spring:
  profiles: local

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  port: 8443

resource:
  redirectUrlTemplate: http://localhost:8080/RedirectPage/child
  authorizationUrl: https://forutona.thkomeet.com:8443/mAuth/oauth/authorize
  tokenUrl: https://forutona.thkomeet.com:8443/mAuth/oauth/token
  userInfoUrl: https://forutona.thkomeet.com:8443/mAuth/getMe
  clientId: forutonaMain
  clientSecret: forutona1020


---
spring:
  profiles: realtest

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

resource:
  redirectUrlTemplate: https://forutona.thkomeet.com:8443/forutonamanagement/RedirectPage/child
  authorizationUrl: https://forutona.thkomeet.com:8443/mAuth/oauth/authorize
  tokenUrl: https://forutona.thkomeet.com:8443/mAuth/oauth/token
  userInfoUrl: https://forutona.thkomeet.com:8443/mAuth/getMe
  clientId: forutonaMain
  clientSecret: forutona1020

---